### ISSUE TITLE
Accidental(?) Custom Fields when modifying organisation

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/zarr-ckan#173]
### What happened?

I went to "Manage" the Fjelltopp organisation (https://zarr.fjelltopp.org/organization/edit/fjelltopp) and I saw this:
![image](https://github.com/user-attachments/assets/f32548a2-387a-4638-8741-8d8a752fa99e)

These custom fields probably need to be removed? I am not sure where they come from?

### Regression Test

- [ ] Of course it is!

### Version

Prod deployed

**Comment by A-Souhei** [comment]
I think these fields are from vanilla CKAN, I remove them.
