### ISSUE TITLE
Short URLs not working on staging

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/zarr-ckan#188]
### What happened?

Looks like short URLs are not working on staging?

![image](https://github.com/user-attachments/assets/97e8bfdb-59d4-4317-b808-2166170724d2)

### Regression Test

- [ ] Of course it is!

### Version

1.4.1 (currently deployed to staging)

**Comment by A-Souhei** [comment]
@ChasNelson1990 ,

to have short_urls work on older datasets (before it was enabled) , we need to run:

`ckan -c ckan.ini short-urls migrate`

**Comment by ChasNelson1990** [comment]
Ah, I understand, thanks
